---
- name: Create the config folder
  file:
    path: "{{ boss__dnsmasq__config_dir }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0755
    state: directory

- name: Create the var folder
  file:
    path: "{{ boss__dnsmasq__var_dir }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0755
    state: directory

- name: Create empty log file
  file:
    path: "{{ boss__dnsmasq__conf_log }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0644
    state: touch
  when: >
    boss__dnsmasq__conf_log is defined and
    boss__dnsmasq__conf_log is not none and
    boss__dnsmasq__conf_log != '-'
  changed_when: False


- block:
  - name: Create DHCP dnsmasq configuration
    template:
      src: dnsmasq.d/dhcp.conf.j2
      dest: "{{ boss__dnsmasq__config_dir }}/dhcp.conf"
      owner: "{{ boss__dnsmasq__user }}"
      group: "{{ boss__dnsmasq__group }}"
      mode: 0644
    notify: reload dnsmasq
    register: boss__dnsmasq__updated_dhcp

  - name: Create TFTP dnsmasq configuration
    template:
      src: dnsmasq.d/tftp.conf.j2
      dest: "{{ boss__dnsmasq__config_dir }}/tftp.conf"
      owner: "{{ boss__dnsmasq__user }}"
      group: "{{ boss__dnsmasq__group }}"
      mode: 0644
    notify: reload dnsmasq
    register: boss__dnsmasq__updated_tftp
    when: dnsmasq_tftp

  when: >
    boss__dnsmasq__conf_dhcp is defined
    and boss__dnsmasq__dhcp


- name: Create global dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: "{{ boss__dnsmasq__config_file }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0644
    validate: 'dnsmasq --test --conf-file=%s'
  notify: reload dnsmasq
  register: boss__dnsmasq__updated_global

- name: Create the dhcp hosts folder
  file:
    path: "{{ dnsmasq_config_dhcphosts | dirname }}"
    owner: "{{ dnsmasq_user }}"
    group: "{{ dnsmasq_group }}"
    mode: 0755
    state: directory
  when: >
    dnsmasq_conf_dhcp_hosts is defined
    and dnsmasq_conf_dhcp_hosts is not none

- name: Create dhcp hosts file from configuration
  template:
    src: leases.j2
    dest: "{{ boss__dnsmasq__config_dhcphosts }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0644
  when: >
    boss__dnsmasq__conf_dhcp_hosts is defined
    and boss__dnsmasq__conf_dhcp_hosts is iterable
  notify: reload dnsmasq

- name: Copy dhcp hosts file if defined
  copy:
    src: "{{ boss__dnsmasq__conf_dhcp_hosts }}"
    dest: "{{ boss__dnsmasq__config_dhcphosts | dirname }}/{{ boss__dnsmasq__conf_dhcp_hosts | basename }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0644
  when: >
    boss__dnsmasq__conf_dhcp_hosts is defined and
    boss__dnsmasq__conf_dhcp_hosts is not iterable
  notify: reload dnsmasq

- name: Copy dhcp script file
  copy:
    src: "{{ boss__dnsmasq__conf_dhcp_script }}"
    dest: "{{ boss__dnsmasq__config_dhcpscript }}"
    owner: root
    group: root
    mode: 0775
  when: >
    boss__dnsmasq__conf_dhcp_script is defined and
    not nsmasq_conf_dhcp_script is none

- name: Create additional hosts file
  template:
    src: hosts.j2
    dest: "{{ boss__dnsmasq__config_addhosts }}"
    owner: "{{ boss__dnsmasq__user }}"
    group: "{{ boss__dnsmasq__group }}"
    mode: 0644
  when: boss__dnsmasq__conf_hosts is defined
  notify: reload dnsmasq

- name: Check if configuration was updated
  set_fact: dnsmasq_updated="{{ boss__dnsmasq__updated_global.changed or boss__dnsmasq__updated_dhcp.changed or boss__dnsmasq__updated_tftp.changed }}"

- name: Ensure dnsmasq is started and enabled on boot
  service:
    name: "{{ boss__dnsmasq__daemon }}"
    state: started
    enabled: "{{ boss__dnsmasq__enabled_on_startup | ternary('yes', 'no') }}"
