---
- name: lookup architecture
  set_fact: architecture="{{ ((ansible_architecture|truncate(3,true,'')) == 'arm') | ternary('ARM','X86') }}"

- name: show architecture
  debug: msg="architecture is set to {{ architecture }}"

- name: Control if the role is supported on this system
  fail: msg="Dnsmasq role is not supported on this system"
  when: >
     ansible_distribution != 'Ubuntu' and
     ansible_distribution != 'CentOS' and
     ansible_distribution != 'Debian' and
     ansible_distribution != 'Red Hat Enterprise Linux'

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["distribution", "packages", "service", "dnsmasq"]

- include: resolvconf.yml
  when: boss__dnsmasq__resolvconf
  tags: ["dnsmasq", "resolvconf"]

- include: install.yml
  tags: ["dnsmasq", "install"]

- include: configure.yml
  tags: ["dnsmasq", "configure"]

- include: tools.yml
  tags: ["dnsmasq", "tools"]
