---
- name: restart dnsmasq
  service: name="{{ boss__dnsmasq__daemon }}" state=restarted

- name: reload dnsmasq
  shell: "kill -s HUP $(cat {{ boss__dnsmasq__pidfile }})"

- name: start dnsmasq
  service: name="{{ boss__dnsmasq__daemon }}" state=started

- name: stop dnsmasq
  service: name="{{ boss__dnsmasq__daemon }}" state=stopped
